### ISSUE TITLE
[question] data fetchers

### ISSUE THREAD

**Issue by xenoterracide** [oguimbal/inversify-graphql#3]
doesn't look like you support these, reading another issue I'm not asking you to (we aren't actually using graphql...) however, do you know of any libraries that do with inversify?

**Comment by oguimbal** [comment]
I do support it... we've been using this lib for years now in my company... but it is stable (that is why there is no recent commit).

I dont know any other library that does that precisely 🤷‍♂️  I would be interested to know, if you find one !

That said, Nestjs has an amazing native support for dependency inejction AND graphql. This is another option if you're looking for a framework that does both (but it wont integrate well with an existing codebase, or another framework)

**Comment by xenoterracide** [comment]
does this support file uploads?

**Comment by oguimbal** [comment]
Being a wrapper around [apollo-server](https://www.npmjs.com/package/apollo-server), it supports everything apollo-server supports.

I've never implemented file uploads via a graphql api so I cant point at any resource, but it is doable.
